"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Bot, Building2, Check, ChevronRight, CircleGauge, Clock3, FileText, Gauge, Globe2, Home as HomeIcon, Lightbulb, LockKeyhole, Menu, MessageSquareText, Search, Send, ShieldCheck, Sparkles, Target, TrendingUp, Users, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider } from "@/components/ui/sidebar";

type Page = "home" | "submit" | "public" | "workspace" | "leadership";
const cases = [
  { id: "UC-1042", title: "AI-assisted supplier risk brief", area: "Procurement", owner: "Nora Chen", impact: "€1.2M", stage: "Scaling", score: 92, tags: ["Risk", "Summarization"], desc: "Produces a daily supplier risk brief from approved market, logistics and internal delivery signals." },
  { id: "UC-1031", title: "Frontline maintenance copilot", area: "Operations", owner: "Elias Berg", impact: "18% less downtime", stage: "Pilot", score: 86, tags: ["Copilot", "Knowledge"], desc: "Helps plant technicians diagnose common faults using validated manuals and prior work orders." },
  { id: "UC-1024", title: "RFP response accelerator", area: "Commercial", owner: "Maya Patel", impact: "9 hrs saved / bid", stage: "Live", score: 90, tags: ["Content", "Sales"], desc: "Drafts compliant responses from approved product claims and past winning proposals." },
  { id: "UC-1019", title: "Invoice exception triage", area: "Finance", owner: "Jon Bell", impact: "64% auto-routed", stage: "Live", score: 88, tags: ["Automation", "Finance"], desc: "Classifies invoice exceptions and routes them with a concise rationale to the right resolver." },
  { id: "UC-1012", title: "People policy navigator", area: "People", owner: "Sofia Rossi", impact: "31% fewer tickets", stage: "Scaling", score: 82, tags: ["Search", "Employee"], desc: "Answers employee policy questions with citations from the controlled HR knowledge base." },
  { id: "UC-1007", title: "Customer call insight miner", area: "Service", owner: "Amir Khan", impact: "+11 NPS insight", stage: "Pilot", score: 79, tags: ["Voice", "Insight"], desc: "Surfaces recurring pain points and coaching opportunities from consented customer calls." },
];
const pipeline = [{ name: "Proposal intake", value: 48, delta: "+12 this month" }, { name: "Discovery", value: 21, delta: "7 awaiting owner" }, { name: "Pilot", value: 14, delta: "4 decisions due" }, { name: "Scale", value: 9, delta: "+2 this quarter" }];
const nav = [{ id: "home" as Page, label: "Home", icon: HomeIcon }, { id: "submit" as Page, label: "Submit an idea", icon: MessageSquareText }, { id: "public" as Page, label: "Public use cases", icon: Globe2 }, { id: "workspace" as Page, label: "Project workspace", icon: LockKeyhole }, { id: "leadership" as Page, label: "Leadership", icon: BarChart3 }];

function Logo() { return <div className="brand-mark" aria-label="AI Use Case Hub"><span>AI</span></div>; }
function Topbar({ title, onMenu }: { title: string; onMenu: () => void }) { return <header className="topbar"><button className="mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu size={20} /></button><div><p className="eyebrow">AI USE CASE HUB</p><h1>{title}</h1></div><div className="top-actions"><button className="search-pill"><Search size={17} /><span>Search hub</span><kbd>⌘ K</kbd></button><button className="avatar" aria-label="User profile">LC</button></div></header>; }
function StatCard({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Gauge }) { return <div className="stat-card"><div className="stat-icon"><Icon size={18} /></div><div><p>{label}</p><strong>{value}</strong><span>{note}</span></div></div>; }

function HomePage({ go }: { go: (p: Page) => void }) { return <div className="page-wrap"><section className="welcome-row"><div><p className="eyebrow red">GOOD MORNING, LINA</p><h2>Turn the next AI idea into measurable value.</h2><p>Explore what already works, submit an opportunity, or review the portfolio.</p></div><Button className="red-button" onClick={() => go("submit")}><Sparkles size={17} /> Share an idea</Button></section><div className="stats-grid"><StatCard label="Active use cases" value="44" note="Across 8 business areas" icon={Lightbulb} /><StatCard label="Value tracked" value="€6.8M" note="Annualized estimate" icon={TrendingUp} /><StatCard label="In pilot" value="14" note="4 decisions due" icon={CircleGauge} /><StatCard label="People involved" value="127" note="Owners & contributors" icon={Users} /></div><section className="two-col"><div className="panel featured-panel"><div className="panel-head"><div><p className="eyebrow">RECOMMENDED FOR YOU</p><h3>Proven ideas worth reusing</h3></div><button onClick={() => go("public")}>View all <ArrowRight size={16}/></button></div><div className="case-list">{cases.slice(0,3).map((item, i) => <button className="case-row" key={item.id} onClick={() => go("public")}><span className="case-index">0{i+1}</span><div><strong>{item.title}</strong><p>{item.area} · {item.impact}</p></div><span className={`stage ${item.stage.toLowerCase()}`}>{item.stage}</span><ChevronRight size={18}/></button>)}</div></div><aside className="panel signal-panel"><div className="signal-orbit"><Bot size={25}/><span/></div><p className="eyebrow red">HUB SIGNAL</p><h3>3 ideas in your network could be combined.</h3><p>Supplier risk, contract review, and RFP response share the same knowledge architecture.</p><button onClick={() => go("submit")}>Explore with AI <ArrowRight size={16}/></button></aside></section><section className="panel momentum"><div><p className="eyebrow">PORTFOLIO MOMENTUM</p><h3>From idea to scale</h3></div><div className="momentum-grid">{pipeline.map((p,i)=><div className="momentum-item" key={p.name}><div><span>0{i+1}</span><strong>{p.value}</strong></div><p>{p.name}</p><small>{p.delta}</small></div>)}</div></section></div>; }

function SubmitPage({ onSubmitted }: { onSubmitted: () => void }) { const [step, setStep] = useState(0); const [text, setText] = useState(""); const [messages, setMessages] = useState([{role:"ai", text:"What work feels slower, harder, or more repetitive than it should? Describe it in your own words."}]); const prompts = ["Who experiences this problem, and how often?", "What would a useful outcome look like — time saved, better quality, lower risk, or something else?", "Got it. I’ve shaped this into an idea brief and checked the hub for overlap."]; function send() { if (!text.trim()) return; const value = text.trim(); setText(""); setMessages(m => [...m, {role:"user",text:value}]); setTimeout(() => { setMessages(m => [...m,{role:"ai",text:prompts[Math.min(step,prompts.length-1)]}]); setStep(s=>s+1); }, 450); } const done = step >= 3; return <div className="submit-layout"><section className="chat-column"><div className="chat-title"><div className="ai-dot"><Sparkles size={18}/></div><div><p className="eyebrow red">IDEA COPILOT</p><h2>Let’s shape your idea</h2></div></div><div className="chat-thread">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><span>{m.role === "ai" ? <Bot size={16}/> : "LC"}</span><p>{m.text}</p></div>)}{done && <div className="result-card"><div className="result-check"><Check size={18}/></div><div><p className="eyebrow red">IDEA BRIEF READY</p><h3>Automated contract obligation tracker</h3><p>Extract obligations and renewal dates from supplier contracts, assign owners, and flag upcoming risks.</p><button onClick={onSubmitted}>Review matches <ArrowRight size={16}/></button></div></div>}</div>{!done && <div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder="Type your answer…" aria-label="Your idea"/><button onClick={send} aria-label="Send"><Send size={18}/></button><small>Enter to send · Your draft is private</small></div>}</section><aside className="brief-column"><p className="eyebrow">LIVE IDEA BRIEF</p><h3>{step ? "Contract obligation tracker" : "Your idea will take shape here"}</h3><div className="brief-rule"/><BriefField label="Problem" value={step>0?"Critical obligations are tracked manually across supplier contracts.":"Listening for the problem…"}/><BriefField label="Users" value={step>1?"Procurement managers and contract owners":"Not defined yet"}/><BriefField label="Value hypothesis" value={step>2?"Reduce missed renewals and cut review time by 60%":"Not defined yet"}/><div className="completeness"><span>Brief completeness</span><strong>{Math.min(25+step*25,100)}%</strong><Progress value={Math.min(25+step*25,100)} /></div></aside></div>; }
function BriefField({label,value}:{label:string,value:string}) { return <div className="brief-field"><span>{label}</span><p>{value}</p></div>; }
function SimilarDialog({ open, onClose, go }: {open:boolean;onClose:()=>void;go:(p:Page)=>void}) { return <Dialog open={open} onOpenChange={onClose}><DialogContent className="match-dialog"><DialogHeader><div className="match-score">87<small>%</small></div><div><p className="eyebrow red">HIGH OVERLAP FOUND</p><DialogTitle>A similar use case already exists</DialogTitle><DialogDescription>Reuse the proven foundation or explain what makes your idea distinct.</DialogDescription></div></DialogHeader><div className="match-card"><div className="match-top"><span>UC-1038</span><span className="stage pilot">Pilot</span></div><h3>Supplier contract intelligence</h3><p>Extracts clauses, renewal dates, and obligations from procurement contracts.</p><div className="match-tags"><span>Same users</span><span>Shared data</span><span>Similar outcome</span></div></div><DialogFooter><Button variant="outline" onClick={()=>{onClose();toast.success("Idea saved as a distinct proposal");}}>Continue as distinct</Button><Button className="red-button" onClick={()=>{onClose();go("workspace");}}>Join existing project</Button></DialogFooter></DialogContent></Dialog>; }

function PublicPage() { const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const filtered=useMemo(()=>cases.filter(c=>(filter==="All"||c.stage===filter)&&(c.title+c.area+c.tags.join(" ")).toLowerCase().includes(query.toLowerCase())),[query,filter]); return <div className="page-wrap"><section className="catalog-head"><div><p className="eyebrow red">PUBLIC LIBRARY</p><h2>Build on what the organization already knows.</h2><p>Reusable use cases, outcomes, and lessons — open to everyone.</p></div><div className="catalog-count"><strong>68</strong><span>published cases</span></div></section><div className="filterbar"><div className="search-box"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search use cases, teams, or capabilities"/></div><Tabs value={filter} onValueChange={setFilter}><TabsList>{["All","Live","Scaling","Pilot"].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList></Tabs></div><div className="cards-grid">{filtered.map(item=><article className="use-card" key={item.id}><div className="use-top"><span>{item.id}</span><span className={`stage ${item.stage.toLowerCase()}`}>{item.stage}</span></div><div className="use-icon"><Building2 size={20}/></div><h3>{item.title}</h3><p>{item.desc}</p><div className="tag-row">{item.tags.map(t=><span key={t}>{t}</span>)}</div><div className="use-footer"><div><small>{item.area}</small><strong>{item.impact}</strong></div><button onClick={()=>toast.info("Use case details opened in preview mode")} aria-label={`Open ${item.title}`}><ArrowRight size={17}/></button></div></article>)}</div></div>; }

function WorkspacePage() { const [tab,setTab]=useState("overview"); return <div className="page-wrap"><section className="workspace-head"><div><div className="secure-label"><LockKeyhole size={14}/> RESTRICTED PROJECT</div><h2>Supplier contract intelligence</h2><p>Project SI-24 · Procurement Excellence</p></div><div className="member-stack"><span>NC</span><span>JP</span><span>EL</span><span>+4</span><Button variant="outline" onClick={()=>toast.success("Invite link copied")}>Invite</Button></div></section><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="workspace-tabs">{["overview","evidence","risks","decisions"].map(x=><TabsTrigger key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</TabsTrigger>)}</TabsList></Tabs><section className="workspace-grid"><div className="panel project-main"><div className="panel-head"><div><p className="eyebrow">CURRENT PHASE</p><h3>{tab === "overview" ? "Validate with real contracts" : tab === "evidence" ? "Evidence library" : tab === "risks" ? "Risk review" : "Decision log"}</h3></div><span className="stage pilot">Pilot</span></div>{tab==="overview"?<><div className="milestone"><div><Check size={16}/></div><div><strong>Data sample approved</strong><p>120 redacted contracts cleared for testing.</p></div><span>Sep 18</span></div><div className="milestone active"><div><Clock3 size={16}/></div><div><strong>Accuracy validation</strong><p>Compare extracted obligations with legal review.</p></div><span>Due Oct 04</span></div><div className="milestone"><div/><div><strong>Scale decision</strong><p>Confirm value, controls, and operating owner.</p></div><span>Oct 16</span></div></>:<WorkspaceTable tab={tab}/>}</div><aside className="panel project-side"><p className="eyebrow">PILOT HEALTH</p><div className="health-score"><strong>82</strong><span>/ 100</span></div><Progress value={82}/><div className="health-row"><span>Value evidence</span><strong>Strong</strong></div><div className="health-row"><span>Data readiness</span><strong>Ready</strong></div><div className="health-row warn"><span>Risk controls</span><strong>Needs review</strong></div><div className="next-action"><Target size={19}/><div><strong>Next action</strong><p>Approve human-review thresholds for renewal alerts.</p></div></div></aside></section></div>; }
function WorkspaceTable({tab}:{tab:string}) { const data:Record<string,string[][]>={evidence:[["Accuracy benchmark","94.2%","Validated"],["User time study","-6.4 hrs/week","Validated"],["Missed renewal baseline","€420k exposure","Draft"]],risks:[["Confidential clauses","Medium","Controlled"],["Extraction error","High","Mitigating"],["Owner assignment","Low","Controlled"]],decisions:[["Pilot scope approved","Sep 06","Nora Chen"],["Model shortlist","Sep 14","Project team"],["Scale gate","Oct 16","SteerCo"]]}; return <div className="simple-table">{data[tab].map((r,i)=><div key={i}>{r.map((c,j)=><span key={j}>{c}</span>)}</div>)}</div>; }

function LeadershipPage() { return <div className="page-wrap"><section className="lead-head"><div><p className="eyebrow red">LEADERSHIP VIEW</p><h2>AI portfolio, at a glance.</h2><p>Value, delivery health, and decisions requiring attention.</p></div><div className="period">FY26 · Q3 <ChevronRight size={15}/></div></section><div className="stats-grid leadership-stats"><StatCard label="Tracked value" value="€6.8M" note="74% benefit confidence" icon={TrendingUp}/><StatCard label="Scale rate" value="38%" note="+9 pts vs. Q2" icon={Gauge}/><StatCard label="Risk reviews" value="6" note="2 need attention" icon={ShieldCheck}/><StatCard label="Decision velocity" value="19 days" note="-4 days vs. Q2" icon={Clock3}/></div><section className="lead-grid"><div className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">VALUE BY BUSINESS AREA</p><h3>Where the portfolio is compounding</h3></div><span>€M annualized</span></div><div className="bars">{[["Operations",2.1,88],["Commercial",1.6,67],["Finance",1.3,54],["Procurement",1.0,42],["People",.8,33]].map(([n,v,w])=><div className="bar-row" key={String(n)}><span>{n}</span><div><i style={{width:`${w}%`}}/></div><strong>€{v}M</strong></div>)}</div></div><div className="panel decision-panel"><p className="eyebrow red">DECISIONS NEEDED</p><h3>3 items need leadership attention</h3>{[["Scale contract intelligence","€820k upside","Oct 04"],["Resolve service data access","4 pilots blocked","Oct 07"],["Consolidate two HR copilots","€180k overlap","Oct 10"]].map((r,i)=><button key={i}><span>0{i+1}</span><div><strong>{r[0]}</strong><p>{r[1]} · {r[2]}</p></div><ChevronRight size={17}/></button>)}</div></section><section className="panel portfolio-table"><div className="panel-head"><div><p className="eyebrow">PORTFOLIO HEALTH</p><h3>Priority initiatives</h3></div><button onClick={()=>toast.success("Portfolio report prepared")}>Export brief <FileText size={16}/></button></div><div className="table-head"><span>Initiative</span><span>Stage</span><span>Owner</span><span>Score</span><span>Value</span></div>{cases.slice(0,4).map(c=><div className="table-row" key={c.id}><strong>{c.title}</strong><span className={`stage ${c.stage.toLowerCase()}`}>{c.stage}</span><span>{c.owner}</span><span>{c.score}/100</span><span>{c.impact}</span></div>)}</section></div>; }

export default function App() { const [page,setPage]=useState<Page>("home"); const [mobile,setMobile]=useState(false); const [match,setMatch]=useState(false); const title=nav.find(n=>n.id===page)?.label||"Home"; const go=(p:Page)=>{setPage(p);setMobile(false);window.scrollTo({top:0,behavior:"smooth"});};
  useEffect(()=>{ const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext; if(!context?.registerTool)return; const lifecycle=new AbortController(); const register=(tool:unknown)=>Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined); void register({name:"navigate_hub_view",title:"Navigate AI Use Case Hub",description:"Open a requested view in the AI Use Case Hub.",inputSchema:{type:"object",properties:{view:{type:"string",enum:["home","submit","public","workspace","leadership"]}},required:["view"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const view=(input as {view?:Page})?.view;if(!view||!nav.some(n=>n.id===view))throw new Error("Unsupported hub view");go(view);return{view,status:"opened"};}}); void register({name:"start_idea_submission",title:"Start idea submission",description:"Open the chatbot-guided idea submission workspace.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){go("submit");return{view:"submit",status:"ready"};}}); return()=>lifecycle.abort(); // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  return <SidebarProvider defaultOpen><div className={mobile?"mobile-open app-shell":"app-shell"}>{mobile&&<button className="mobile-overlay" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}<Sidebar collapsible="none" className="hub-sidebar"><SidebarHeader className="side-head"><Logo/><div><strong>Use Case Hub</strong><span>Enterprise AI</span></div><button className="side-close" onClick={()=>setMobile(false)}><X size={18}/></button></SidebarHeader><SidebarContent><SidebarMenu className="nav-menu">{nav.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton isActive={page===item.id} onClick={()=>go(item.id)}><item.icon/><span>{item.label}</span>{item.id==="workspace"&&<LockKeyhole className="nav-lock"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-label">YOUR ACTIVITY</div><div className="activity"><span className="pulse"/><div><strong>Contract tracker</strong><p>Draft · updated now</p></div></div></SidebarContent><SidebarFooter><div className="side-help"><Sparkles size={17}/><div><strong>AI assistant</strong><span>Mock mode</span></div><span className="status-dot"/></div><p className="prototype-note">MVP · Data shown is illustrative</p></SidebarFooter></Sidebar><SidebarInset className="main-area"><Topbar title={title} onMenu={()=>setMobile(true)}/>{page==="home"&&<HomePage go={go}/>} {page==="submit"&&<SubmitPage onSubmitted={()=>setMatch(true)}/>} {page==="public"&&<PublicPage/>} {page==="workspace"&&<WorkspacePage/>} {page==="leadership"&&<LeadershipPage/>}</SidebarInset><SimilarDialog open={match} onClose={()=>setMatch(false)} go={go}/><Toaster position="bottom-right" richColors/></div></SidebarProvider>; }
