"use client";

import { useState } from "react";
import { Bot, ChevronRight, MessageSquareText, Send, Sparkles, ThumbsUp } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const reviewCases = [
  { id:"UC-1042", title:"AI-assisted supplier risk brief", area:"Procurement", owner:"Nora Chen", impact:"€1.2M", score:92, desc:"Produces a daily supplier risk brief from approved market, logistics and internal delivery signals." },
  { id:"UC-1031", title:"Frontline maintenance copilot", area:"Operations", owner:"Elias Berg", impact:"18% less downtime", score:86, desc:"Helps plant technicians diagnose common faults using validated manuals and prior work orders." },
  { id:"UC-1012", title:"People policy navigator", area:"People", owner:"Sofia Rossi", impact:"31% fewer tickets", score:82, desc:"Answers employee policy questions with citations from the controlled HR knowledge base." },
];

export function ManagerReviewPage() {
  const [selected, setSelected] = useState(reviewCases[0]);
  const [feedback, setFeedback] = useState("");
  const [decision, setDecision] = useState<"pending"|"approved"|"changes">("pending");
  const [chatInput, setChatInput] = useState("");
  const [chat, setChat] = useState([{role:"ai",text:`I’ve reviewed ${reviewCases[0].title}. Ask me to compare similar use cases, explore opportunities, or surface delivery risks.`}]);
  const selectCase = (item: typeof reviewCases[number]) => { setSelected(item); setDecision("pending"); setFeedback(""); setChat([{role:"ai",text:`I’ve reviewed ${item.title}. Ask me to compare similar use cases, explore opportunities, or surface delivery risks.`}]); };
  const ask = (question?: string) => { const prompt=(question||chatInput).trim(); if(!prompt)return; setChatInput(""); setChat(m=>[...m,{role:"user",text:prompt}]); const lower=prompt.toLowerCase(); const reply=lower.includes("compare")||lower.includes("similar") ? `${selected.title} is closest to “Supplier contract intelligence” (74% overlap). Both use governed knowledge and human review, but this proposal has a stronger external-risk signal and a clearer value hypothesis.` : lower.includes("risk") ? "The main risks are source freshness, false-positive alerts, and unclear escalation ownership. A four-week pilot with human approval and weekly precision checks would address them." : "A strong next step is a narrow pilot for one team. Measure hours saved, earlier issue detection, and the percentage of outputs accepted without major edits."; setTimeout(()=>setChat(m=>[...m,{role:"ai",text:reply}]),350); };
  const decide = (next:"approved"|"changes") => { setDecision(next); toast.success(next==="approved"?"Use case approved for discovery":"Feedback sent to the use case owner"); };
  return <div className="review-page"><section className="review-head"><div><p className="eyebrow red">MANAGER REVIEW</p><h2>Review the idea. Challenge it with AI. Make the call.</h2><p>Give the owner clear feedback, compare existing work, and decide what moves forward.</p></div><div className="review-summary"><strong>3</strong><span>awaiting review</span></div></section><div className="review-layout"><aside className="review-queue"><div className="queue-title"><span>REVIEW QUEUE</span><strong>3</strong></div>{reviewCases.map((item,i)=><button key={item.id} className={selected.id===item.id?"review-case active":"review-case"} onClick={()=>selectCase(item)}><span className="case-order">0{i+1}</span><div><strong>{item.title}</strong><p>{item.area} · {item.owner}</p></div><ChevronRight size={17}/></button>)}</aside><main className="review-work"><section className="review-brief"><div className="review-brief-top"><div><span>{selected.id}</span><h3>{selected.title}</h3><p>{selected.desc}</p></div><span className={`decision-status ${decision}`}>{decision==="approved"?"Approved":decision==="changes"?"Changes requested":"Awaiting decision"}</span></div><div className="review-evidence"><div><span>Value hypothesis</span><strong>{selected.impact}</strong></div><div><span>Readiness score</span><strong>{selected.score}/100</strong></div><div><span>Business owner</span><strong>{selected.owner}</strong></div></div><label className="feedback-box"><span>Feedback to the owner</span><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="What is strong? What needs clarification before this moves forward?"/></label><div className="decision-actions"><Button variant="outline" onClick={()=>decide("changes")}><MessageSquareText size={16}/> Request changes</Button><Button className="approve-button" onClick={()=>decide("approved")}><ThumbsUp size={16}/> Approve for discovery</Button></div></section><section className="manager-ai"><div className="manager-ai-head"><div className="ai-dot"><Sparkles size={17}/></div><div><p className="eyebrow red">MANAGER COPILOT</p><h3>Explore this use case</h3></div></div><div className="quick-prompts"><button onClick={()=>ask("Compare similar use cases")}>Compare similar cases</button><button onClick={()=>ask("Explore the opportunity")}>Explore opportunity</button><button onClick={()=>ask("What are the key risks?")}>Surface risks</button></div><div className="manager-chat">{chat.map((m,i)=><div key={i} className={`manager-message ${m.role}`}><span>{m.role==="ai"?<Bot size={15}/>:"LC"}</span><p>{m.text}</p></div>)}</div><div className="manager-composer"><Input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask();}} placeholder="Ask anything about this use case…"/><button onClick={()=>ask()} aria-label="Ask manager copilot"><Send size={17}/></button></div></section></main></div></div>;
}
